// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace Yaaaap
{
public static class GooglePlay
{
        public const string achievement_adaptation_is_over = "CgkIlNi06e8CEAIQEA"; // <GPGSID>
        public const string achievement_welcome_sky = "CgkIlNi06e8CEAIQGQ"; // <GPGSID>
        public const string achievement_welcome_castle = "CgkIlNi06e8CEAIQGA"; // <GPGSID>
        public const string achievement_you_are_yaaaap_conqueror = "CgkIlNi06e8CEAIQFg"; // <GPGSID>
        public const string achievement_its_time_to_run_yaaaap = "CgkIlNi06e8CEAIQAQ"; // <GPGSID>
        public const string achievement_run_is_not_over = "CgkIlNi06e8CEAIQEQ"; // <GPGSID>
        public const string achievement_welcome_sea = "CgkIlNi06e8CEAIQGg"; // <GPGSID>
        public const string achievement_you_are_invincible_man = "CgkIlNi06e8CEAIQFw"; // <GPGSID>
        public const string achievement_im_you_you_are_me = "CgkIlNi06e8CEAIQDA"; // <GPGSID>
        public const string achievement_im_yaaaap_beginner = "CgkIlNi06e8CEAIQFQ"; // <GPGSID>
        public const string achievement_staggered_you_and_me = "CgkIlNi06e8CEAIQBQ"; // <GPGSID>
        public const string achievement_welcome_hell = "CgkIlNi06e8CEAIQGw"; // <GPGSID>
        public const string achievement_we_should_break_up = "CgkIlNi06e8CEAIQDg"; // <GPGSID>
        public const string achievement_this_is_teamwork = "CgkIlNi06e8CEAIQCw"; // <GPGSID>
        public const string achievement_come_out_person_who_said_easy = "CgkIlNi06e8CEAIQAg"; // <GPGSID>
        public const string achievement_im_running_man = "CgkIlNi06e8CEAIQAw"; // <GPGSID>
        public const string achievement_its_now_being_adapted = "CgkIlNi06e8CEAIQDw"; // <GPGSID>
        public const string achievement_im_marathoner = "CgkIlNi06e8CEAIQBA"; // <GPGSID>
        public const string leaderboard_yaaaap_ = "CgkIlNi06e8CEAIQCA"; // <GPGSID>
        public const string achievement_you_are_legend = "CgkIlNi06e8CEAIQFA"; // <GPGSID>
        public const string achievement_fusion = "CgkIlNi06e8CEAIQDQ"; // <GPGSID>

}
}
